//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataformaVirutalEducativa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Inscripcion = new HashSet<Inscripcion>();
            this.Notificacion = new HashSet<Notificacion>();
            this.Sesion = new HashSet<Sesion>();
        }
    
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public string Titulo { get; set; }
        public string Categoria { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Inicio { get; set; }
        public int Duracion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Cupo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        public virtual ICollection<Sesion> Sesion { get; set; }
    }
}
