//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataformaVirutalEducativa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public int IdCurso { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
