//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataformaVirutalEducativa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Comentario = new HashSet<Comentario>();
            this.Curso = new HashSet<Curso>();
            this.Inscripcion = new HashSet<Inscripcion>();
            this.Material = new HashSet<Material>();
            this.Mensaje = new HashSet<Mensaje>();
        }
    
        public int Id { get; set; }
        public int IdUserRoles { get; set; }
        public string Nickname { get; set; }
        public string Password { get; set; }
        public string Repass { get; set; }
        public string Estado { get; set; }
        public string CI { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public string Nombres { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual ICollection<Comentario> Comentario { get; set; }
        public virtual ICollection<Curso> Curso { get; set; }
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
        public virtual ICollection<Material> Material { get; set; }
        public virtual ICollection<Mensaje> Mensaje { get; set; }
    }
}
